dataset: faust
backend: satr+glip
backend_type: detection_based
dataset_dir: "data/demo"

region_names: "['weights', 'handle']"
object_class: "dumbell"

satr:
  gaussian_reweighting: true
  face_smoothing: true
  face_smoothing_n_ring: 5
  sam: false
  geodesic_from_point_cloud: true
  per_face: false
  octree_level: 7

camera:
  n_views: 10
  frontview_std: 4
  frontview_center: [3.14, 0.0]
  render_res: 1024
  random_rendering: False

color: "vertex normals"

background: [255.0, 255.0, 255.0]
