dataset: faust
backend: satr+glip
backend_type: detection_based
dataset_dir: "data/demo"

# region_names: "['cover', 'binding', 'pages', 'elastic band']"
region_names: "['cover', 'pages']"
object_class: "notebook"

satr:
  gaussian_reweighting: true
  face_smoothing: true
  face_smoothing_n_ring: 5
  sam: true
  geodesic_from_point_cloud: true

camera:
  n_views: 10
  frontview_std: 4
  frontview_center: [3.14, 0.0]
  render_res: 1024
  random_rendering: false

background: [255., 255., 255.]

color: "vertex normals"
